<?php
/*session_start();
$purc_head="purc_head".$_SESSION['s_fyear'];
$purc_item="purc_item".$_SESSION['s_fyear'];
$invoice_head="invoice_head".$_SESSION['s_fyear'];
$invoice_item="invoice_item".$_SESSION['s_fyear'];
$ch_head="ch_head".$_SESSION['s_fyear'];
$ch_item="ch_item".$_SESSION['s_fyear'];
$expense="expense".$_SESSION['s_fyear'];
$payment="payment".$_SESSION['s_fyear'];
$receipt="receipt".$_SESSION['s_fyear'];
$bank_tran="bank_tran".$_SESSION['s_fyear'];
$opbal="op_bal".$_SESSION['s_fyear'];
$crnote_head="crnte_head".$_SESSION['s_fyear'];
$crnote_item="crnote_item".$_SESSION['s_fyear'];
$crnote="crnote".$_SESSION['s_fyear'];
$drnote="drnote".$_SESSION['s_fyear'];
$dbnote_head="dbnote_head".$_SESSION['s_fyear'];
$dbnote_item="dbnote_item".$_SESSION['s_fyear'];
$stock="stock".$_SESSION['s_fyear'];
$stock_adj="stock_adj".$_SESSION['s_fyear'];
$stock_tran="stock_tran".$_SESSION['s_fyear'];
$stock_recv="stock_recv".$_SESSION['s_fyear'];
$batch="batch".$_SESSION['s_fyear'];*/
?>